### ISSUE TITLE
todits tfc.tv addon not working version 0.0.40

### ISSUE THREAD

**Issue by rc3851** [todits-xbmc/todits-xbmc-tv#18] opened 2015-09-28 04:30 UTC
Tfc.tv addon not working. Getting media error message "subcription expired". I'm using version 0.0.40.

Thanks.

**Comment by todits-xbmc** [comment] 2015-09-28 23:30
Duplicate of https://github.com/todits-xbmc/todits-xbmc-tv/issues/17

**Closed by todits-xbmc** 2015-09-28 23:30 UTC
